#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include "qt_include.h"
#include "settings.h"
#include "communication.h"

namespace Ui {
    class MainWindow;
}


class MainWindow : public QMainWindow
{
    Q_OBJECT
    
public:
    explicit MainWindow(QWidget *parent = 0);
    ~MainWindow();

private:
    /* ui*/
    Ui::MainWindow *ui;
    /* forms*/
    Settings *formSettings;

    CommunicationProvider *mamba;
    quint8 currentAddress;// current device address;
    QDateTime extDateTime(QString text);

    enum {StateDisconnected, StateRequestConnect, StateConfigRead, StateConnected,StateLiveView} conState;

    void closeEvent(QCloseEvent *);
    void setupCustomUi();        
    void loadConfigurationList(void);
    void request_config(void);    
    void processStatus(quint32 val);
    void saveUiState(void);
    void loadUiState(void);
    void enableTester(bool en);


private slots:
    void slot_ActivityTX(bool on);
    void slot_ActivityRX(bool on);
    void slot_CommandAnswer(quint8 cmd,quint32 cmd_p,bool ok);
    void slot_ApplyTriggers();
    void slot_TamperSourceClicked();
    void slot_Print(const QString text);
    void slot_PrintTestMode(const QString text);
    void slot_PopulateUi();
    void slot_completedOperation();
    void slot_UpdateUIState();
    void slot_runStream(bool);
    void slot_ConnectSensor(bool checked);
    void slot_SaveFile();
    void slot_LoadFile();
    void slot_ClearData();
    void slot_About();
    void slot_Settings();
    void slot_SetSensitivity();
    void slot_SetProfileN();
    void slot_shutdownSession(void);
    void slot_UpdateFirmware(void);
    /* generated by system*/
    void on_remove_cfg_btn_clicked();
    void on_tofile_btn_clicked();    
    void on_defsetting_btn_clicked();
    void on_fromdevice_btn_clicked();
    void on_pwrtrig_cmb_currentIndexChanged(int index);
    void on_didown_cmb_currentIndexChanged(int index);    
    void on_acc_sens_sl_sliderReleased();
    void on_pushButton_5_clicked();
    void on_pushButton_clicked();
    void on_pushButton_3_clicked();
    void on_pushButton_2_clicked();
    void on_sendtxtcmd_btn_clicked();
    void on_alarm_lst_clicked(const QModelIndex &index);    


    void on_btnApplySavedConfig_clicked();
};

#endif // MAINWINDOW_H
